syntax = "proto3";
package proto;

option go_package = "protocol/";

message TransportBundle {
  repeated Ny Packets = 1;
}

message Ny {
  message Update {
    string RouterId = 1;
    bytes Prefix = 2;
    uint32 Seqno = 3;
    uint32 Metric = 4;
    string Tag = 5;
  }
  message AckRetract {
    bytes Prefix = 1;
    string Tag = 2;
  }
  message SeqnoRequest {
    string RouterId = 1;
    bytes Prefix = 2;
    uint32 Seqno = 3;
    uint32 HopCount = 4;
    string Tag = 5;
  }

  message Probe {
    uint64 Token = 1;
    optional uint64 ResponseToken = 2;
  }

  oneof type {
    Update RouteOp = 1;
    SeqnoRequest SeqnoRequestOp = 2;
    Probe ProbeOp = 3;
    AckRetract AckRetractOp = 4;
  }
}
